Repository PM-Auth2-Gateway/JS-Admin, pull requests merged in 2021-03, with the labels that each got.

#2 Precommit hooks configuration
  .eslintrc
  .prettierrc
  package-lock.json
  package.json
  src/App.jsx
  src/App.test.jsx
Labels: review

#7 Navigation
  package-lock.json
  package.json
  public/index.html
  src/App.jsx
  src/App.module.scss
  src/components/AppPreview/AppPreview.test.jsx
  src/components/Navigation/Navigation.jsx
  src/components/Navigation/Navigation.module.scss
  src/components/Navigation/Navigation.test.jsx
  src/components/Navigation/__snapshots__/Navigation.test.jsx.snap
  src/hooks/useFacebookAuth.jsx
Labels: enhancement, review

#11 jwt token added
  package.json
  src/axiosConfig.js
  src/components/LoginButton/LoginButton.jsx
  src/components/Navigation/Navigation.jsx
  src/components/Navigation/Navigation.test.jsx
  src/components/Navigation/__snapshots__/Navigation.test.jsx.snap
  src/hooks/useFacebookAuth.jsx
  src/services/LocalStorageService.js
  src/services/LoginApiService.js
Labels: enhancement, review

#8 App crud logic
  package-lock.json
  package.json
  src/components/AppInfo/AppInfo.jsx
  src/components/AppInfo/AppInfo.selector.js
  src/components/AppInfo/AppInfo.test.jsx
  src/components/AppInfo/__snapshots__/AppInfo.test.jsx.snap
  src/components/AppList/AppList.jsx
  src/components/AppList/AppList.selector.js
  src/components/AppList/AppList.test.jsx
  src/components/AppList/__snapshots__/AppList.test.jsx.snap
  src/components/AppPreview/AppPreview.jsx
  src/components/CreateAppModal/CreateAppModal.jsx
  src/components/CreateAppModal/CreateAppModal.test.jsx
  src/components/CreateAppModal/__snapshots__/CreateAppModal.test.jsx.snap
  src/components/DeleteAppModal/DeleteAppModal.jsx
  src/components/DeleteAppModal/DeleteAppModal.test.jsx
  src/components/DeleteAppModal/__snapshots__/DeleteAppModal.test.jsx.snap
  src/components/EditAppForm/EditAppForm.jsx
  src/components/EditAppForm/EditAppForm.test.jsx
  src/components/EditAppForm/__snapshots__/EditAppForm.test.jsx.snap
  src/config.js
  src/ducks/.gitkeep
  src/ducks/apps/all.js
  src/ducks/apps/current.js
  src/index.js
  src/services/.gitkeep
  src/services/AppsApiService.js
  src/services/SocialsApiService.js
  src/store/index.js
Labels: review

#15 fixes forms validation
  src/components/CreateAppModal/CreateAppModal.jsx
  src/components/SocialModal/SocialModal.jsx
  src/data/empty_social.json
Labels: bug

#14 Private Routes
  src/components/PrivateRoute/PrivateRoute.jsx
  src/components/PrivateRoute/PrivateRoute.selector.js
Labels: enhancement, review

#13 Social auth
  src/axiosConfig.js
  src/components/AppInfo/AppInfo.jsx
  src/components/Login/Login.jsx
  src/components/Login/Login.module.scss
  src/components/Login/Login.selector.js
  src/components/Login/Login.test.js
  src/components/Login/__snapshots__/Login.test.js.snap
  src/components/LoginButton/LoginButton.jsx
  src/components/Navigation/Navigation.jsx
  src/components/Navigation/Navigation.module.scss
  src/components/Navigation/__snapshots__/Navigation.test.jsx.snap
  src/ducks/apps/all.js
  src/ducks/apps/current.js
  src/ducks/auth/socials.js
  src/ducks/auth/user.js
  src/services/AppsApiService.js
  src/services/LocalStorageService.js
  src/services/LoginApiService.js
  src/services/SocialsApiService.js
  src/store/index.js
Labels: enhancement, review

#12 Refactoring
  package.json
  src/App.jsx
  src/App.module.scss
  src/components/AppInfo/AppInfo.jsx
  src/components/AppInfo/AppInfo.module.scss
  src/components/AppInfo/AppInfo.selector.js
  src/components/AppInfo/AppInfo.test.jsx
  src/components/AppInfo/__snapshots__/AppInfo.test.jsx.snap
  src/components/AppList/AppList.jsx
  src/components/AppList/AppList.selector.js
  src/components/AppList/__snapshots__/AppList.test.jsx.snap
  src/components/AppPreview/AppPreview.jsx
  src/components/AppPreview/AppPreview.module.scss
  src/components/AppPreview/__snapshots__/AppPreview.test.jsx.snap
  src/components/AppSocialsInfo/AppSocialsInfo.jsx
  src/components/AppSocialsInfo/AppSocialsInfo.test.jsx
  src/components/AppSocialsInfo/__snapshots__/AppSocialsInfo.test.jsx.snap
  src/components/BackButton/BackButton.jsx
  src/components/BackButton/BackButton.test.jsx
  src/components/BackButton/__snapshots__/BackButton.test.jsx.snap
  src/components/CreateAppModal/CreateAppModal.jsx
  src/components/CreateAppModal/CreateAppModal.test.jsx
  src/components/CreateAppModal/__snapshots__/CreateAppModal.test.jsx.snap
  src/components/DeleteAppForm/DeleteAppForm.jsx
  src/components/DeleteAppForm/DeleteAppForm.test.jsx
  src/components/DeleteAppForm/__snapshots__/DeleteAppForm.test.jsx.snap
  src/components/EditAppForm/EditAppForm.jsx
  src/components/Login/Login.jsx
  src/components/Login/Login.test.js
  src/components/Login/__snapshots__/Login.test.js.snap
  src/components/Navigation/Navigation.jsx
  src/components/Navigation/__snapshots__/Navigation.test.jsx.snap
  src/components/SocialInfo/SocialInfo.jsx
  src/components/SocialInfo/SocialInfo.module.scss
  src/components/SocialInfo/SocialInfo.test.jsx
  src/components/SocialInfo/__snapshots__/SocialInfo.test.jsx.snap
  src/components/SocialModal/SocialModal.jsx
  src/components/SocialModal/SocialModal.selector.js
  src/components/SocialPreview/SocialPreview.jsx
  src/components/SocialPreview/SocialPreview.module.scss
  src/components/SocialPreview/SocialPreview.test.jsx
  src/components/SocialPreview/__snapshots__/SocialPreview.test.jsx.snap
  src/components/SocialsList/SocialsList.jsx
  src/components/SocialsList/SocialsList.selector.js
  src/components/SocialsList/SocialsList.test.jsx
  src/components/SocialsList/__snapshots__/SocialsList.test.jsx.snap
  src/contexts/App.context.js
  src/ducks/apps/all.js
  src/ducks/apps/current.js
  src/ducks/apps/index.js
  src/ducks/socials/all.js
  src/ducks/socials/current.js
  src/ducks/socials/index.js
  src/pages/ApplicationsPage/ApplicationsPage.jsx
  src/pages/SingleApplicationPage/SingleApplicationPage.jsx
  src/pages/SingleApplicationPage/SingleApplicationPage.module.scss
  src/services/SocialsApiService.js
  src/store/index.js
  src/styles/.gitkeep
  src/styles/Scroll.mixin.scss
Labels: review

#16 Added logos for socials
  src/components/Login/Login.jsx
Labels: enhancement, review

#17 Docs page
  package-lock.json
  package.json
  src/App.jsx
  src/pages/DocsPage/AndroidDoc/AndroidDoc.jsx
  src/pages/DocsPage/DocsPage.jsx
  src/pages/DocsPage/DocsPage.module.scss
  src/pages/DocsPage/IOSDoc/IOSDoc.jsx
  src/pages/DocsPage/WebDoc/WebDoc.jsx
Labels: documentation, enhancement, review

#19 fixed z-index and indentation
  src/components/Login/Login.module.scss
  src/pages/DocsPage/DocsPage.jsx
Labels: fix

#18 fix redirect to main after page refresh
  src/components/PrivateRoute/PrivateRoute.jsx
Labels: fix

#20 Guide page
  src/App.jsx
  src/App.module.scss
  src/pages/DocsPage/DocsPage.module.scss
  src/pages/GuidePage/FacebookGuide/FacebookGuide.jsx
  src/pages/GuidePage/GoogleGuide/GoogleGuide.jsx
  src/pages/GuidePage/GuidePage.jsx
Labels: documentation, review

#21 added notifications
  package-lock.json
  package.json
  src/App.jsx
  src/components/CustomToastContainer/CustomToastContainer.jsx
  src/components/CustomToastContainer/CustomToastContainer.test.jsx
  src/components/CustomToastContainer/__snapshots__/CustomToastContainer.test.jsx.snap
  src/components/Login/Login.jsx
  src/components/Login/__snapshots__/Login.test.js.snap
  src/ducks/apps/all.js
  src/ducks/apps/current.js
  src/ducks/auth/user.js
  src/ducks/socials/all.js
  src/ducks/socials/current.js
Labels: enhancement, review

#22 Fix layout
  src/components/AppInfo/AppInfo.jsx
  src/components/AppList/AppList.jsx
  src/components/CreateAppModal/CreateAppModal.jsx
  src/components/EditAppForm/EditAppForm.jsx
  src/components/Preloader/Preloader.jsx
  src/components/Preloader/Preloader.module.scss
  src/components/SocialsList/SocialsList.jsx
  src/pages/SingleApplicationPage/SingleApplicationPage.jsx
Labels: fix, review

#24 added redirect to apps from home page after login
  src/components/Login/Login.jsx
Labels: enhancement, review

#28 Nav fix
  src/components/Login/Login.test.js
  src/components/Login/__snapshots__/Login.test.js.snap
  src/components/Navigation/Navigation.jsx
  src/components/Navigation/Navigation.module.scss
  src/components/Navigation/__snapshots__/Navigation.test.jsx.snap
Labels: fix
